### ISSUE TITLE
Meta: Better Temporary Name

### ISSUE THREAD

**Issue by bubby932** [bubby932/hn_demo#2]
Ideas:
- Cobalt
- pickle (case sensitive !!!!)
- Crimbie
- Impulse

**Comment by MindlessSea** [comment]
Further ideas:
MiniOS
BasicBlend
CoreDrive
Learnix
UtilitOS
Simplex
FoundryOS

**Comment by bubby932** [comment]
ratio

**Comment by bubby932** [comment]
- Cobalt.

**Comment by MindlessSea** [comment]
you seriously gonna name your OS the same as a dead programming language?

jk good name choice

**Comment by bubby932** [comment]
thats COBOL but ok

**Comment by MindlessSea** [comment]
sorry - my brain did not exist 12 hours ago (at like 8AM)

**Comment by MindlessSea** [comment]
i only got 3 hours of sleep

**Comment by bubby932** [comment]
rip
